# Generated by Django 4.2.16 on 2024-12-27 15:11
import json

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def load_ingredients(apps, schema_editor):
    """Загрузка данных Ингридиентов."""
    Ingredient = apps.get_model('recipes', 'Ingredient')

    with open('./data/ingredients.json', 'r', encoding='utf-8') as file:
        data = json.load(file)

        for item in data:
            new_ingredient = Ingredient(
                name=item['name'],
                measurement_unit=item['measurement_unit']
            )
            new_ingredient.save()


def load_tags(apps, schema_editor):
    """Загрузка данных Тэгов."""
    Tag = apps.get_model('recipes', 'Tag')

    with open('./data/tags.json', 'r', encoding='utf-8') as file:
        data = json.load(file)

        for item in data:
            new_tag = Tag(
                name=item['name'],
                slug=item['slug']
            )
            new_tag.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='cart_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='recipe_ingredient', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(
                through='recipes.RecipeIngredient', to='recipes.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(
                to='recipes.tag', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='favorite', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.RunPython(load_ingredients),
        migrations.RunPython(load_tags),
    ]
